'use client';"
"
import { useState } from 'react';"
import Link from 'next/link';"
import { usePathname } from 'next/navigation';"
import {"
  LayoutDashboard,"
  Users,"
  Calendar,"
  FileText,"
  CreditCard,"
  Settings,"
  Menu,"
  X,"
  Search,"
  Bell"
} from 'lucide-react';"
import { cn } from '@/lib/utils';"
"
const navigation = ["
  { name: 'Dashboard', href: '/', icon: LayoutDashboard },"
  { name: 'Patients', href: '/patients', icon: Users },"
  { name: 'Appointments', href: '/appointments', icon: Calendar },"
  { name: 'Cases', href: '/cases', icon: FileText },"
  { name: 'Treatments', href: '/treatments', icon: FileText },"
  { name: 'Billing', href: '/billing', icon: CreditCard },"
  { name: 'Settings', href: '/settings', icon: Settings },"
];"
"
interface DashboardLayoutProps {"
  children: React.ReactNode;"
}"
"
export default function DashboardLayout({ children }: DashboardLayoutProps) {"
  const [sidebarOpen, setSidebarOpen] = useState(false);"
  const pathname = usePathname();"
"
  return ("
    <div className="min-h-screen bg-gray-50">"
      {/* Mobile sidebar overlay */}"
      {sidebarOpen && ("
        <div"
          className="fixed inset-0 z-40 bg-gray-900/50 lg:hidden""
          onClick={() => setSidebarOpen(false)}"
        />"
      )}"
"
      {/* Sidebar */}"
      <div className={cn("
        "fixed inset-y-0 left-0 z-50 w-64 bg-white border-r border-gray-200 transform transition-transform duration-200 ease-in-out lg:translate-x-0","
        sidebarOpen ? "translate-x-0" : "-translate-x-full""
      )}>"
        <div className="flex h-full flex-col">"
          {/* Logo */}"
          <div className="flex h-16 items-center justify-between px-6 border-b border-gray-200">"
            <div className="flex items-center space-x-2">"
              <div className="h-8 w-8 bg-blue-600 rounded-lg flex items-center justify-center">"
                <span className="text-white font-bold text-sm">DC</span>"
              </div>"
              <span className="text-xl font-bold text-gray-900">DentalCare</span>"
            </div>"
            <button"
              className="lg:hidden""
              onClick={() => setSidebarOpen(false)}"
            >"
              <X className="h-6 w-6 text-gray-400" />"
            </button>"
          </div>"
"
          {/* Navigation */}"
          <nav className="flex-1 px-4 py-6 space-y-2">"
            {navigation.map((item) => {"
              const isActive = pathname === item.href ||"
                (item.href !== '/' && pathname.startsWith(item.href));"
"
              return ("
                <Link"
                  key={item.name}"
                  href={item.href}"
                  className={cn("
                    "flex items-center px-3 py-2 text-sm font-medium rounded-lg transition-colors","
                    isActive"
                      ? "bg-blue-50 text-blue-700""
                      : "text-gray-700 hover:bg-gray-100""
                  )}"
                >"
                  <item.icon className="mr-3 h-5 w-5" />"
                  {item.name}"
                </Link>"
              );"
            })}"
          </nav>"
        </div>"
      </div>"
"
      {/* Main content */}"
      <div className="lg:ml-64">"
        {/* Top bar */}"
        <header className="bg-white border-b border-gray-200">"
          <div className="flex h-16 items-center justify-between px-6">"
            <div className="flex items-center space-x-4">"
              <button"
                className="lg:hidden""
                onClick={() => setSidebarOpen(true)}"
              >"
                <Menu className="h-6 w-6 text-gray-400" />"
              </button>"
"
              {/* Search */}"
              <div className="relative hidden sm:block">"
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />"
                <input"
                  type="text""
                  placeholder="Search patients, cases...""
                  className="pl-10 pr-4 py-2 w-64 text-sm border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent""
                />"
              </div>"
            </div>"
"
            <div className="flex items-center space-x-4">"
              {/* Notifications */}"
              <button className="relative p-2 text-gray-400 hover:text-gray-600">"
                <Bell className="h-5 w-5" />"
                <span className="absolute top-1 right-1 h-2 w-2 bg-red-500 rounded-full"></span>"
              </button>"
"
              {/* User menu */}"
              <div className="flex items-center space-x-3">"
                <div className="h-8 w-8 bg-blue-500 rounded-full flex items-center justify-center">"
                  <span className="text-white text-sm font-medium">Dr</span>"
                </div>"
                <div className="hidden sm:block">"
                  <p className="text-sm font-medium text-gray-900">Admin</p>"
                  <p className="text-xs text-gray-500">Clinic</p>"
                </div>"
              </div>"
            </div>"
          </div>"
        </header>"
"
        {/* Page content */}"
        <main className="p-6">"
          {children}"
        </main>"
      </div>"
    </div>"
  );"
}"
